import AboutPageContent from "./AboutPage";
export const metadata = {
  title: "About us",
  description: "Generated by create next app",
};
const AboutPage = () => {
  return (
    <div>
      <AboutPageContent />
    </div>
  );
};

export default AboutPage;
